# Generated by Django 3.0.5 on 2020-08-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonmbre', models.CharField(max_length=25)),
                ('ArchivoZip', models.FileField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'Añadir Persona',
            },
        ),
    ]
