# Generated by Django 3.0.5 on 2020-08-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frweb', '0002_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubirVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonmbre', models.CharField(max_length=25)),
                ('Video', models.FileField(upload_to='videos/')),
            ],
            options={
                'verbose_name': 'Añadir Video',
            },
        ),
    ]
