# Generated by Django 3.0.5 on 2020-09-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frweb', '0005_auto_20200909_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconocidos',
            options={'verbose_name': 'Reconocido', 'verbose_name_plural': 'Reconocidos'},
        ),
        migrations.RemoveField(
            model_name='reconocidos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id',
        ),
        migrations.AlterField(
            model_name='reconocidos',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
