# Generated by Django 3.0.5 on 2020-10-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frweb', '0006_auto_20200910_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_image',
            new_name='imagen',
        ),
    ]
