# Generated by Django 3.0.5 on 2020-10-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frweb', '0007_auto_20201013_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
