# Generated by Django 3.0.5 on 2020-10-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frweb', '0008_remove_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subirvideo',
            name='nonmbre',
        ),
    ]
