# Generated by Django 3.1.1 on 2020-11-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frweb', '0009_remove_subirvideo_nonmbre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='SubirImagen',
        ),
    ]
