# Generated by Django 3.1.1 on 2020-11-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frweb', '0010_auto_20201102_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconocidos',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Reconocido', 'verbose_name_plural': 'Reconocidos'},
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='fotos',
        ),
        migrations.AddField(
            model_name='reconocidos',
            name='fotos',
            field=models.CharField(default='empty', max_length=3),
            preserve_default=False,
        ),
    ]
