# Generated by Django 3.1.1 on 2020-11-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frweb', '0011_auto_20201117_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconocidos',
            options={'verbose_name': 'Reconocido', 'verbose_name_plural': 'Reconocidos'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nonmbre',
            new_name='nombre',
        ),
    ]
